apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app1
  namespace: default
  labels:
    app: my-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app1
  template:
    metadata:
      labels:
        app: my-app1
    spec:
      containers:
      - name: my-app1
        image: 741448935198.dkr.ecr.ap-south-1.amazonaws.com/yogeshecrrepo:47aad0ee345cdc2f2b5361fb31b4b69835b273e2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
